In [1]:
import pandas
import matplotlib.pyplot as plt
import numpy as np

In [120]:
df = pandas.read_csv('fatal-police-shootings-data.csv')

In [96]:
demo = pandas.read_csv('acs2017_county_data.csv')

In [97]:
c = ['State','County', 'TotalPop', 'Hispanic', 'White', 'Black', 'Native', 'Asian', 'Pacific']
demo = demo[c]

In [94]:
demo['Pacific'] = demo['Pacific'].replace({0.0:1}, inplace=True)

In [98]:
demo['H'] = demo['TotalPop'] * demo['Hispanic'] //100
demo['W'] = demo['TotalPop'] * demo['White'] //100
demo['B'] = demo['TotalPop'] * demo['Black'] //100
demo['N'] = demo['TotalPop'] * demo['Native'] //100
demo['A'] = demo['TotalPop'] * demo['Asian'] //100
demo['O'] = demo['TotalPop'] * demo['Pacific'] //100

In [50]:
demo[demo is np.nan] = 1.0

In [99]:
demo

,State,County,TotalPop,Hispanic,White,Black,Native,Asian,Pacific,H,W,B,N,A,O
0,Alabama,Autauga County,55036,2.7,75.4,18.9,0.3,0.9,0.0,1485.0,41497.0,10401.0,165.0,495.0,0.0
1,Alabama,Baldwin County,203360,4.4,83.1,9.5,0.8,0.7,0.0,8947.0,168992.0,19319.0,1626.0,1423.0,0.0
2,Alabama,Barbour County,26201,4.2,45.7,47.8,0.2,0.6,0.0,1100.0,11973.0,12524.0,52.0,157.0,0.0
3,Alabama,Bibb County,22580,2.4,74.6,22.0,0.4,0.0,0.0,541.0,16844.0,4967.0,90.0,0.0,0.0
4,Alabama,Blount County,57667,9.0,87.4,1.5,0.3,0.1,0.0,5190.0,50400.0,865.0,173.0,57.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3215,Puerto Rico,Vega Baja Municipio,54754,96.7,3.1,0.1,0.0,0.0,0.0,52947.0,1697.0,54.0,0.0,0.0,0.0
3216,Puerto Rico,Vieques Municipio,8931,95.7,4.0,0.0,0.0,0.0,0.0,8546.0,357.0,0.0,0.0,0.0,0.0
3217,Puerto Rico,Villalba Municipio,23659,99.7,0.2,0.1,0.0,0.0,0.0,23588.0,47.0,23.0,0.0,0.0,0.0
3218,Puerto Rico,Yabucoa Municipio,35025,99.9,0.1,0.0,0.0,0.0,0.0,34989.0,35.0,0.0,0.0,0.0,0.0
3219,Puerto Rico,Yauco Municipio,37585,99.8,0.2,0.0,0.0,0.0,0.0,37509.0,75.0,0.0,0.0,0.0,0.0

In [128]:
demo_state = demo.groupby(['State']).sum()

In [129]:
demo_state

,TotalPop,Hispanic,White,Black,Native,Asian,Pacific,H,W,B,N,A,O
State,,,,,,,,,,,,,
Alabama,4850771,221.0,4366.3,1921.1,40.7,47.7,1.2,198385.0,3197877.0,1280323.0,22671.0,61659.0,926.0
Alaska,738565,147.7,1404.2,34.2,917.2,173.5,15.8,50301.0,454526.0,22330.0,101633.0,44754.0,8646.0
Arizona,6809946,463.3,762.4,27.2,198.5,19.4,1.9,2103443.0,3785517.0,277136.0,264780.0,208375.0,11879.0
Arkansas,2977944,381.8,5672.6,1209.9,40.5,51.9,5.8,213373.0,2174088.0,457312.0,17022.0,42027.0,6770.0
California,38982847,1744.1,3176.2,170.8,95.7,410.1,16.9,15106298.0,14778217.0,2162560.0,138859.0,5430051.0,135141.0
Colorado,5436519,1282.4,4778.1,94.9,53.2,71.0,7.3,1157255.0,3732129.0,210545.0,28541.0,161308.0,8206.0
Connecticut,3594478,91.4,608.3,51.8,1.0,28.6,0.0,551634.0,2445050.0,350815.0,4407.0,154355.0,0.0
Delaware,943732,25.6,196.1,60.3,1.2,8.6,0.0,84886.0,594704.0,201571.0,3010.0,36019.0,0.0
District of Columbia,672391,10.7,36.0,46.9,0.2,3.7,0.0,71945.0,242060.0,315351.0,1344.0,24878.0,0.0
Florida,20278447,919.6,4564.1,951.5,26.5,103.4,5.1,5018436.0,11125455.0,3127564.0,43189.0,533912.0,8024.0
Georgia,10201635,991.1,9947.7,4475.0,30.2,191.0,7.3,950783.0,5469991.0,3150604.0,18516.0,386750.0,3025.0
Hawaii,1421658,48.6,130.0,4.0,0.7,153.8,72.3,145317.0,315735.0,24275.0,1759.0,526234.0,130995.0
Idaho,1657375,559.4,3648.5,16.6,66.7,28.4,3.8,202237.0,1367881.0,10476.0,17866.0,22059.0,1974.0
Illinois,12854526,492.0,8878.9,525.1,15.7,124.6,2.1,2164387.0,7956874.0,1806111.0,15127.0,665544.0,645.0
Indiana,6614418,357.0,8349.4,244.6,17.3,92.6,2.0,442107.0,5280597.0,604159.0,12660.0,136589.0,1008.0
Iowa,3118102,449.4,9047.6,136.5,29.2,107.2,6.0,178240.0,2697079.0,104219.0,8656.0,70622.0,2830.0
Kansas,2903820,1024.2,8897.8,183.6,81.8,84.4,5.7,334702.0,2220079.0,163648.0,18854.0,79741.0,1164.0
Kentucky,4424376,276.2,11017.2,437.9,21.9,61.6,3.1,152237.0,3764145.0,348039.0,7881.0,59505.0,1321.0
Louisiana,4663461,223.4,3950.7,2033.6,39.5,51.7,1.3,231931.0,2752252.0,1490453.0,24521.0,80209.0,620.0
Maine,1330158,22.6,1510.3,12.4,12.3,12.4,0.2,20551.0,1244811.0,16106.0,7820.0,14595.0,84.0
Maryland,5996079,140.0,1634.8,476.1,4.6,79.1,0.6,573474.0,3108923.0,1754667.0,10777.0,371258.0,1156.0
Massachusetts,6789319,125.9,1089.6,79.8,4.0,56.4,0.3,761088.0,4953125.0,453520.0,8979.0,424630.0,293.0
Michigan,9925568,287.2,7312.2,321.6,104.8,82.8,1.4,484606.0,7493089.0,1358353.0,44859.0,287185.0,761.0
Minnesota,5490726,372.0,7737.6,141.8,168.4,125.2,2.6,284999.0,4434544.0,321125.0,51586.0,254836.0,588.0
Mississippi,2986220,196.4,4453.9,3390.3,41.8,42.1,1.3,88093.0,1702272.0,1118613.0,12432.0,28723.0,297.0
Missouri,6075300,322.5,10415.2,409.6,57.4,72.6,9.7,244517.0,4849176.0,698165.0,22924.0,112162.0,5654.0
Montana,1029862,162.4,4848.1,12.4,435.3,26.2,1.7,36490.0,891957.0,4168.0,64137.0,7228.0,468.0
Nebraska,1893921,608.6,8324.6,76.1,110.8,47.8,6.7,197937.0,1511826.0,87062.0,12746.0,41770.0,1163.0
Nevada,2887725,294.4,1229.0,37.2,65.6,34.5,3.8,814666.0,1456803.0,242502.0,24509.0,228685.0,18119.0
New Hampshire,1331848,23.2,929.5,10.2,1.9,18.2,0.2,45547.0,1211299.0,16309.0,1788.0,33263.0,121.0
New Jersey,8960161,355.7,1311.3,238.1,2.1,149.2,0.1,1764304.0,5023740.0,1136185.0,7979.0,837418.0,679.0
New Mexico,2084828,1563.6,1385.5,41.4,227.1,25.0,0.7,1004177.0,796019.0,37065.0,181496.0,27714.0,1153.0
New York,19798228,474.2,5041.9,360.3,23.2,175.3,1.2,3725979.0,11076573.0,2844456.0,41237.0,1636533.0,1027.0
North Carolina,10052564,709.2,6811.1,2016.3,154.9,113.9,3.6,914630.0,6397493.0,2127516.0,109345.0,266972.0,3358.0
North Dakota,745475,147.4,4643.2,46.5,348.6,26.2,1.0,24831.0,638774.0,17041.0,38703.0,10020.0,191.0
Ohio,11609756,230.2,7945.1,359.1,12.9,82.0,1.7,414003.0,9244378.0,1410297.0,15769.0,233996.0,1860.0
Oklahoma,3896251,679.7,5460.3,260.1,685.2,58.3,8.5,394607.0,2588723.0,278575.0,276822.0,79623.0,5750.0
Oregon,4025127,422.2,2913.6,26.5,61.8,57.7,9.6,509228.0,3079196.0,72632.0,34789.0,164659.0,14557.0
Pennsylvania,12790505,280.6,5913.0,302.0,8.3,96.6,0.2,874625.0,9880951.0,1357588.0,15085.0,413475.0,266.0
Puerto Rico,3468963,7715.2,64.2,3.8,0.4,3.5,0.1,3432457.0,26129.0,2601.0,35.0,2445.0,17.0
Rhode Island,1056138,37.3,421.7,15.0,1.6,12.5,0.3,153863.0,773167.0,57684.0,3956.0,35122.0,842.0
South Carolina,4893444,206.8,2622.0,1632.6,16.3,37.0,2.2,266716.0,3120393.0,1321296.0,13111.0,71016.0,2970.0
South Dakota,855444,169.7,5292.1,36.7,916.9,47.4,4.1,29986.0,707252.0,14183.0,71034.0,11612.0,292.0
Tennessee,6597381,321.9,8211.0,689.0,24.6,64.9,4.0,340351.0,4899128.0,1099798.0,14612.0,109570.0,2921.0
Texas,27419612,8767.7,14365.7,1561.1,84.7,249.1,17.0,10674355.0,11751358.0,3198836.0,69698.0,1224238.0,21537.0
Utah,2993941,259.4,2475.0,12.6,79.4,22.8,9.0,409319.0,2365680.0,31917.0,27968.0,67283.0,26331.0
Vermont,624636,23.5,1319.5,11.8,4.9,12.7,0.3,11235.0,582377.0,7415.0,1796.0,9555.0,126.0
Virginia,8365952,682.1,9534.0,2446.9,35.0,274.3,4.1,749247.0,5238696.0,1575279.0,17201.0,516742.0,3689.0
Washington,7169967,546.0,2978.7,48.4,78.8,104.3,11.2,882765.0,5001604.0,251283.0,79916.0,573578.0,45463.0
West Virginia,1836843,67.1,5193.7,126.6,9.8,24.0,1.1,27116.0,1694764.0,64510.0,3119.0,13843.0,367.0
Wisconsin,5763217,263.5,6427.8,114.7,192.6,87.3,1.6,380836.0,4715393.0,359818.0,46674.0,151657.0,672.0
Wyoming,583200,187.9,1995.7,13.4,40.6,17.3,0.9,56663.0,491642.0,5759.0,11912.0,4912.0,385.0

In [106]:
us = demo_state.sum()
us

H     59951158.0
W    197305511.0
B     39449815.0
N      2096110.0
A     16990909.0
O       486331.0
dtype: float64

In [130]:
c2 = ['TotalPop', 'H', 'W', 'B', 'N', 'A', 'O']
demo_state = demo_state[c2]

In [155]:
demo_state = demo_state.drop(demo_state.index[-13])

In [156]:
s2 = demo_state[['TotalPop']]

In [14]:
crime = pandas.read_csv('state data.csv')

In [34]:
crime

            Pop  Poverty RateÂ   Median Home ValueÂ   Mean Household IncomeÂ
state
AK       734002         0.1061              265200                   96499
TX     29472300         0.1430              161700                   84221
CA     39937500         0.1374              475900                  101493
MT      1086760         0.1280              219600                   70959
NM      2096640         0.1957              166800                   66565
AZ      7378490         0.1480              209600                   77221
NV      3139660         0.1253              242400                   77319
CO      5845530         0.1010              313600                   92520
OR      4301090         0.1314              287300                   80040
WY       567025         0.1117              213300                   79257
MI     10045000         0.1450              146200                   75352
MN      5700670         0.0960              211800                   90600
UT      3282120         0.0944              256700                   87053
ID      1826160         0.1253              192300                   70620
KS      2910360         0.1204              145400                   77509
NE      1952570         0.1095              147800                   77278
SD       903027         0.1253              159100                   73768
WA      7797100         0.1054              311700                   93847
ND       761723         0.1041              185000                   84043
OK      3954820         0.1537              130900                   70262
MO      6169270         0.1358              151600                   73145
FL     21993000         0.1357              196800                   76652
WI      5851750         0.1142              173600                   77687
GA     10736100         0.1497              166800                   78574
IL     12659700         0.1292              187200                   88857
IA      3179850         0.1112              142300                   75951
NY     19440500         0.1439              302200                   97424
NC     10611900         0.1436              165900                   73753
AR      3039000         0.1679              123300                   64272
AL      4908620         0.1690              137200                   67243
LA      4645180         0.1891              157800                   68823
MS      2989260         0.2006              114500                   60640
PA     12820900         0.1232              174100                   81549
OH     11747700         0.1401              140000                   74109
VA      8626210         0.1036              264900                   98000
TN      6897580         0.1517              158600                   71458
KY      4499690         0.1716              135300                   67110
IN      6745350         0.1347              135400                   71912
ME      1345790         0.1202              184500                   73210
SC      5210100         0.1479              154800                   70093
WV      1778070         0.1774              115000                   61225
MD      6083120         0.0910              305500                  107482
HI      1412690         0.0973              587700                   99765
MA      6976600         0.1018              366800                  106627
VT       628061         0.1067              223700                   78472
NH      1371250         0.0746              252800                   95876
NJ      8936570         0.1012              327900                  110140
CT      3563080         0.0978              272700                  109693
NaN     3032160         0.4931              113500                   32190
DE       982895         0.1117              244700                   86962
RI      1056160         0.1260              249800                   85527
NaN      720687         0.1519              568400                  121698

In [33]:
crime = crime[['Pop','Poverty Rate\xa0','Median Home Value\xa0','Mean Household Income\xa0']]

In [25]:
crime = crime.set_index('State')

In [28]:
us_state_abbrev = {
'Alabama': 'AL', 'Alaska': 'AK', 'Arizona': 'AZ', 'Arkansas': 'AR', 'California': 'CA', 'Colorado': 'CO',
'Connecticut': 'CT', 'Delaware': 'DE', 'Washington DC':'DC', 'Florida': 'FL', 'Georgia': 'GA', 'Hawaii': 'HI', 'Idaho': 'ID',
'Illinois': 'IL', 'Indiana': 'IN', 'Iowa': 'IA', 'Kansas': 'KS', 'Kentucky': 'KY', 'Louisiana': 'LA',
'Maine': 'ME', 'Maryland': 'MD', 'Massachusetts': 'MA', 'Michigan': 'MI', 'Minnesota': 'MN', 'Mississippi': 'MS',
'Missouri': 'MO', 'Montana': 'MT', 'Nebraska': 'NE', 'Nevada': 'NV', 'New Hampshire': 'NH', 'New Jersey': 'NJ',
'New Mexico': 'NM', 'New York': 'NY', 'North Carolina': 'NC', 'North Dakota': 'ND', 'Ohio': 'OH', 'Oklahoma': 'OK',
'Oregon': 'OR', 'Pennsylvania': 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC', 'South Dakota': 'SD',
'Tennessee': 'TN', 'Texas': 'TX', 'Utah': 'UT', 'Vermont': 'VT', 'Virginia': 'VA', 'Washington': 'WA',
'West Virginia': 'WV', 'Wisconsin': 'WI', 'Wyoming': 'WY'}
crime['state'] = crime.index.to_series().map(us_state_abbrev)

In [29]:
crime = crime.set_index('state')

In [35]:
crime.to_csv('state_data2.csv')

In [158]:
s2 = s2.set_index('state')

In [159]:
s2

       TotalPop
state
AL      4850771
AK       738565
AZ      6809946
AR      2977944
CA     38982847
CO      5436519
CT      3594478
DE       943732
DC       672391
FL     20278447
GA     10201635
HI      1421658
ID      1657375
IL     12854526
IN      6614418
IA      3118102
KS      2903820
KY      4424376
LA      4663461
ME      1330158
MD      5996079
MA      6789319
MI      9925568
MN      5490726
MS      2986220
MO      6075300
MT      1029862
NE      1893921
NV      2887725
NH      1331848
NJ      8960161
NM      2084828
NY     19798228
NC     10052564
ND       745475
OH     11609756
OK      3896251
OR      4025127
PA     12790505
RI      1056138
SC      4893444
SD       855444
TN      6597381
TX     27419612
UT      2993941
VT       624636
VA      8365952
WA      7169967
WV      1836843
WI      5763217
WY       583200

In [121]:
state = df.groupby(['state']).count()

In [123]:
state = state[['id']]

In [145]:
state

        id
state
AK      39
AL     104
AR      83
AZ     254
CA     799
CO     195
CT      21
DC      13
DE      13
FL     350
GA     182
HI      30
IA      32
ID      42
IL     104
IN      95
KS      50
KY      95
LA     109
MA      35
MD      79
ME      22
MI      78
MN      61
MO     141
MS      65
MT      31
NC     156
ND      11
NE      24
NH      13
NJ      68
NM     106
NV      96
NY     101
OH     155
OK     164
OR      88
PA     108
RI       4
SC      88
SD      17
TN     139
TX     481
UT      60
VA      95
VT       9
WA     152
WI      91
WV      54
WY      14

In [160]:
state['ppl'] = s2['TotalPop'].tolist()

/mnt/c/Users/ljh23/python_venv/v1/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [162]:
state['per million'] = state['id']/state['ppl'] * 1000000

/mnt/c/Users/ljh23/python_venv/v1/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [164]:
state.to_csv('412 state per capita.csv')

In [103]:
race = df.groupby(['race']).count()

In [107]:
race['ppl'] = us

In [111]:
c3 = ['id', 'ppl']
race = race[c3]

In [113]:
race['per capita'] = race['id']/race['ppl']

/mnt/c/Users/ljh23/python_venv/v1/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [115]:
race = race.drop(race.index[4])

In [117]:
race['per million'] = race['per capita'] * 1000000

In [119]:
race.to_csv('normalize by population.csv')